import {images} from './theme';

const FIRESTORE_KEYS = {
  // storage folder name
  STORAGE_NAME: 'images',

  // common filed
  DOCUMENT_ID: 'documentID',

  // user filed
  EMAIL: 'email',
  HEIGHTS: 'height',
  SHIRT_SIZE: 'shirt_size',
  DENIM_SIZE: 'denim_size',
  STYLE_TEXT: 'no_go',
  INSPIRATION_TEXT: 'style_preference',
  PHOTO_URL: 'photoURL', // exist in the photos collection

  // box filed -> collection of products
  BOX_CREATED_AT: 'createdAt',
  BOX_FEEDBACK_SAVED: 'feedbackSaved',

  // product filed -> box item
  PRODUCT_NAME: 'name',
  PRODUCT_DESCRIPTION: 'description',
  PRODUCT_FEEDBACK: 'feedback',
  PRODUCT_SERIAL: 'serial',
  IMGAE_URL: 'imageURL',

  // collection name for feedback
  COLLECTION_GOOD: 'liked_items',
  COLLECTION_NOT_MY_STYLE: 'unliked_items',
  COLLECTION_TOO_BIG: 'too_big',
  COLLECTION_TOO_SMALL: 'too_small',
  COLLECTION_KEPT_ONE_MONTH: 'kept1month',
  COLLECTION_KEPT_SIX_MONTHS: 'kept6months',

  // other collections
  COLLECTION_USERS: 'users',
  COLLECTION_BOXES: 'boxes',
  COLLECTION_ITEMS: 'items',
  COLLECTION_PHOTOS: 'photos',
};

// Local storage
const LOCAL_STORAGE = {
  EMAIL: 'email',
  TOKEN: 'token',
  FCM_TOKEN: 'fcmToken',
};

// Profile Screen
const PROFILE = {
  HEIGHTS: [
    {label: '151', value: '151'},
    {label: '152', value: '152'},
    {label: '150', value: '150'},
    {label: '153', value: '153'},
    {label: '154', value: '154'},
    {label: '155', value: '155'},
    {label: '156', value: '156'},
    {label: '157', value: '157'},
    {label: '158', value: '158'},
    {label: '159', value: '159'},
    {label: '160', value: '160'},
    {label: '161', value: '161'},
    {label: '162', value: '162'},
    {label: '163', value: '163'},
    {label: '164', value: '164'},
    {label: '165', value: '165'},
    {label: '166', value: '166'},
    {label: '167', value: '167'},
    {label: '168', value: '168'},
    {label: '169', value: '169'},
    {label: '170', value: '170'},
    {label: '171', value: '171'},
    {label: '172', value: '172'},
    {label: '173', value: '173'},
    {label: '174', value: '174'},
    {label: '175', value: '175'},
    {label: '176', value: '176'},
    {label: '177', value: '177'},
    {label: '178', value: '178'},
    {label: '170', value: '170'},
    {label: '180', value: '180'},
    {label: '181', value: '181'},
    {label: '182', value: '182'},
    {label: '183', value: '183'},
    {label: '184', value: '184'},
    {label: '185', value: '185'},
    {label: '186', value: '186'},
    {label: '187', value: '187'},
    {label: '188', value: '188'},
    {label: '189', value: '189'},
    {label: '190', value: '190'},
  ],
  SHIRT_SIZES: [
    {label: 'XS', value: 'XS'},
    {label: 'XS,S', value: 'XS,S'},
    {label: 'S', value: 'S'},
    {label: 'S,M', value: 'S,M'},
    {label: 'M', value: 'M'},
    {label: 'M,L', value: 'M,L'},
    {label: 'L', value: 'L'},
    {label: 'L,XL', value: 'L,XL'},
    {label: 'XL', value: 'XL'},
    {label: 'XL,XXL', value: 'XL,XXL'},
    {label: 'XXL', value: 'XXL'},
    {label: 'XXL,XXXL', value: 'XXL,XXXL'},
    {label: 'XXXL', value: 'XXXL'},
  ],
  DENIM_SIZES: [
    {label: '34', value: '34'},
    {label: '34,36', value: '34,36'},
    {label: '36', value: '36'},
    {label: '36,38', value: '36,38'},
    {label: '38', value: '38'},
    {label: '38,40', value: '38,40'},
    {label: '40', value: '40'},
    {label: '40,42', value: '40,42'},
    {label: '42', value: '42'},
    {label: '42,44', value: '42,44'},
    {label: '44', value: '44'},
    {label: '44,46', value: '44,46'},
    {label: '46', value: '46'},
  ],
};

// Feedback scren
const FEEDBACK = {
  FEEDBACK_GOOD: 'Liked it',
  FEEDBACK_NOT_MY_STYLE: 'Not my style',
  FEEDBACK_TOO_BIG: 'Too big',
  FEEDBACK_TOO_SMALL: 'Too small',
  FEEDBACK_KEPT_ONE_MONTH: 'Kept for 1 more month',
  FEEDBACK_KEPT_SIX_MONTHS: 'Kept for 6 more months',
};

const FEEDBACK_OPTIONS = [
  {
    label: FEEDBACK.FEEDBACK_GOOD,
    value: FIRESTORE_KEYS.COLLECTION_GOOD,
  },
  {
    label: FEEDBACK.FEEDBACK_NOT_MY_STYLE,
    value: FIRESTORE_KEYS.COLLECTION_NOT_MY_STYLE,
  },
  {
    label: FEEDBACK.FEEDBACK_TOO_BIG,
    value: FIRESTORE_KEYS.COLLECTION_TOO_BIG,
  },
  {
    label: FEEDBACK.FEEDBACK_TOO_SMALL,
    value: FIRESTORE_KEYS.COLLECTION_TOO_SMALL,
  },
  {
    label: FEEDBACK.FEEDBACK_KEPT_ONE_MONTH,
    value: FIRESTORE_KEYS.COLLECTION_KEPT_ONE_MONTH,
  },
  {
    label: FEEDBACK.FEEDBACK_KEPT_SIX_MONTHS,
    value: FIRESTORE_KEYS.COLLECTION_KEPT_SIX_MONTHS,
  },
];

const HOME_DATA = {
  TITLE: 'Hey there!\nWelcome to your profile',
  DESCRIPTION:
    'Here you can update your info and give feedback on your boxes. We also love to get inspirational pictures from you. It helps a lot!',
  PICTURE_TITLE: 'Press a pricture longer to delete it.',
};

const PROFILE_DATA = {
  TYPE_TITLE: 'What type of clothes do you want?',
  TYPE_DATA: [
    {label: 'I prefer basics.', value: 'I prefer basics.'},
    {
      label: 'I have basics, I need something more.',
      value: 'I have basics, I need something more.',
    },
    {label: 'I would like a mix', value: 'I would like a mix'},
    {label: 'I want complete outfits', value: 'I want complete outfits'},
  ],
  FEEL_TITLE: 'How do you want to feel in your clothes?',
  FEEL_DATA: [
    {label: 'Professional', value: 'Professional'},
    {label: 'Casual', value: 'Casual'},
    {label: 'Comfortable', value: 'Comfortable'},
    {label: 'Feminine', value: 'Feminine'},
    {label: 'Non-binary', value: 'Non-binary'},
    {label: 'Trendy', value: 'Trendy'},
  ],
  TOPS_TITLE: 'How do you like the cut of the tops?',
  TOPS_DESCRIPTION: 'Select as many as you want.',
  TOPS_DATA: [
    {label: 'Long', value: 'Long', img: images.LONG, aspectRatio: 1.2},
    {label: 'Cropped', value: 'Cropped', img: images.CROPPED},
    {label: 'Tight', value: 'Tight', img: images.TIGHT},
    {label: 'Loose', value: 'Loose', img: images.LOOSE},
    {label: 'Classic', value: 'Classic', img: images.CLASSIC},
    {label: 'Oversized', value: 'Oversized', img: images.OVERSIZED},
    {label: 'C-collar', value: 'C-collar', img: images.CREW_NECK},
    {label: 'V-collar', value: 'V-collar', img: images.V_NECK},
  ],
  TOPS_BUTTON_TITLE: "I don't wear dresses or skirt",
  DRESSES_TITLE: 'How do you like the cut of your dressess & skirts?',
  DRESSES_DESCRIPTION: 'Select as many as you want.',
  DRESSES_DATA: [
    {label: 'Loose', value: 'Loose', img: images.LOOSE_DRESSES},
    {label: 'High waist', value: 'High waist', img: images.HIGH_WAIST},
    {label: 'Long', value: 'Long', img: images.LONG_DRESS, aspectRatio: 1.2},
    {
      label: 'Classic Length',
      value: 'Classic length',
      img: images.CLASSIC_LENGTH,
      aspectRatio: 1.2,
    },
    {label: 'Tight', value: 'Tight', img: images.TIGHT_DRESSES},
    {label: 'Short', value: 'Short', img: images.SHORT_DRESS},
  ],
  DRESSES_BUTTON_TITLE: "I don't wear dresses or skirt",
  JUMPERS_TITLE: 'Which ones are your favourite jumpers & knitted pullover?',
  JUMPERS_DESCRIPTION: 'Select as many as you want.',
  JUMPERS_DATA: [
    {label: 'Turtle necks', value: 'Turtle-necks', img: images.TURTLE_NECK},
    {label: 'Jumpers', value: 'Jumpers', img: images.JUMPERS},
    {label: 'Cardigans', value: 'Cardigans', img: images.CARDIGANS},
    {
      label: 'Long lines',
      value: 'Long-lines',
      img: images.LONE_LINES,
      aspectRatio: 1.2,
    },
  ],
  KIND_TITLE: 'What do you look for the most in clothes?',
  KIND_DESCRIPTION: '1 meaning super casual and 5 business like.',
  KIND_DATA: [
    {label: 'Prints', value: 'Prints'},
    {label: 'Bright Colors', value: 'Bright Colors'},
    {label: 'Dark Colors', value: 'Dark Colors'},
    {label: 'Light Colors', value: 'Light Colors'},
    {label: 'Minimal Tones', value: 'Minimal Tones'},
    {label: 'Edgy Details', value: 'Edgy Details'},
  ],
  NO_GO_TYPES_TITLE: 'What are your NO-GOs in print and Patterns?',
  NO_GO_TYPES_DESCRIPTION: "Stuff that you really don't want to receive",
  NO_GO_TYPES_DATA: [
    {label: 'Lace', value: 'Lace', img: images.LACE},
    {label: 'Polka Dots', value: 'Polka Dots', img: images.POLKA_DOTS},
    {label: 'Animal prints', value: 'Animal Prints', img: images.ANIMAL_PRINTS},
    {label: 'Stripes', value: 'Stripes', img: images.STRIPES},
    {label: 'Retro prints', value: 'Retro Prints', img: images.RETRO},
    {label: 'Flowers prints', value: 'Flower Prints', img: images.FLOWERS},
    {
      label: 'Geometric Prints',
      value: 'Geometric Prints',
      img: images.GEOMETRIC,
    },
    {label: 'Checked prints', value: 'Checked Prints', img: images.CHECKED},
  ],
  NO_GO_COLORS_TITLE: 'Which colours are NO-GOs for you?',
  NO_GO_COLORS_DESCRIPTION: "Stuff that you really don't want to receive",
  NO_GO_COLORS_DATA: [
    {label: 'Purple', value: 'Purple'},
    {label: 'Beige', value: 'Beige'},
    {label: 'Pink', value: 'Pink'},
    {label: 'Red', value: 'Red'},
    {label: 'Silver', value: 'Silver'},
    {label: 'Brown', value: 'Brown'},
    {label: 'Orange', value: 'Orange'},
    {label: 'Green', value: 'Green'},
    {label: 'Gold', value: 'Gold'},
    {label: 'White', value: 'White'},
    {label: 'Yellow', value: 'Yellow'},
    {label: 'Blue', value: 'Blue'},
    {label: 'Grey', value: 'Grey'},
    {label: 'Black', value: 'Black'},
  ],
  STYLES_TITLE: 'Which brands are the closest to the style that you like?',
  STYLES_DESCRIPTION: 'We will use them as inspiration',
  STYLES_DATA: [
    {label: 'MONKI', value: 'MONKI'},
    {label: 'COS', value: 'COS'},
    {label: 'VILA', value: 'VILA'},
    {label: 'ZARA', value: 'ZARA'},
    {label: 'ADIDAS', value: 'ADIDAS'},
    {label: 'LEVI’S', value: "LEVI\u005C'S"},
    {label: 'WEEKDAY', value: 'WEEKDAY'},
    {label: 'FLIPPA K', value: 'FILIPPA K'},
    {label: 'MANGO', value: 'MANGO'},
    {label: 'CARIN WESTER', value: 'CARIN WESTER'},
    {label: 'NA-KD', value: 'NA-KD'},
    {label: '& OTHER STORIES', value: '& OTHER STORIES'},
    {label: 'ÅHLENS', value: 'ÅHLENS'},
    {label: 'SAMSOE & SAMSOE', value: 'SAMSOE & SAMSOE'},
    {label: 'VITANGE/ RETRO', value: 'VINTAGE/ RETRO'},
    {label: 'Other', value: 'Other'},
  ],
  JEWELLERY_TITLE: 'What is your preferred tone of jewellery?',
  JEWELLERY_DESCRIPTION: 'Select at least 3',
  JEWELLERY_DATA: [
    {label: 'Silver', value: 'Silver'},
    {label: 'Gold', value: 'Gold'},
    {label: 'Both', value: 'Both'},
  ],
  COMFORTABLE_STYLES_TITLE: 'Which styles are you the most comfortable with?',
  COMFORTABLE_STYLES_DESCRIPTION: "Stuff that you really don't want to receive",
  COMFORTABLE_STYLES_DATA: [
    {label: 'Purple', value: 'Purple'},
    {label: 'Beige', value: 'Beige'},
    {label: 'Pink', value: 'Pink'},
    {label: 'Red', value: 'Red'},
    {label: 'Silver', value: 'Silver'},
    {label: 'Brown', value: 'Brown'},
    {label: 'Orange', value: 'Orange'},
    {label: 'Green', value: 'Green'},
    {label: 'Gold', value: 'Gold'},
    {label: 'White', value: 'White'},
    {label: 'Yellow', value: 'Yellow'},
    {label: 'Blue', value: 'Blue'},
    {label: 'Grey', value: 'Grey'},
    {label: 'Black', value: 'Black'},
  ],
  HEIGHT_TITLE: "What's your height?",
  HEIGHT_DESCRIPTION: 'in cm',
  SIZE_TITLE: "What's your shirt size?",
  SIZE_DESCRIPTION: 'You can pick a range if that makes sense to you.',
  DENIM_TITLE: "What's your denim size?",
  DENIM_DESCRIPTION: 'You can pick a range if that makes sense to you.',
  FIT_TITLE:
    'Is there anything else we should know about your fit and body shape?',
  FIT_DESCRIPTION: 'Optional',
  FIT_DATA: [
    {label: 'Large hips', value: 'Large hips'},
    {label: 'Small waist', value: 'Small waist'},
    {label: 'Broad shoulders', value: 'Broad shoulders'},
    {label: 'Round Waist', value: 'Round waist'},
    {label: 'Broad chest', value: 'Broad chest'},
    {label: 'Long arms', value: 'Long arms'},
  ],
  YEAR_TITLE: 'How old do you feel?',
  YEAR_DATA: [
    {label: '18-24', value: '18-24'},
    {label: '25-34', value: '25-34'},
    {label: '35-44', value: '35-44'},
    {label: '45-54', value: '45-54'},
    {label: '55+', value: '55+'},
  ],
  CONTACT_TITLE: 'Alright! Now we need your shipping details and contact info',
  CONTACT_DESCRIPTION:
    "Bare with us, it's the end of your style profile. The nex page is for your payment methods and then you'll be all set",
  EMAIL_TITLE: "What's your email address?",
  EMAIL_DESCRIPTION: 'So we can send you invoices and important informations',
  NAME_TITLE: 'First and Last name',
  SUBSCRIBE_TITLE: 'Subscribe for 19 SEK/MONTH',
  PAYMENT_SUCCESS: 'Your payment was successful!',
  ADD_SUCCESS: 'Your card added successful!',
  PAYMENT_FAILED: 'Your payment was failed',
  PAYMENT_CONTENT:
    'Boxes are being shipped every month. Feel free to reach out if you have any concerns',
  PAYMENT_CONTACT:
    'Our live chat is available on weekdays from 09:00 to 18:00 at Getyourboxes.com',
  CARD_TITLE: 'Enter your card information',
  CARD_ADD:
    'Your card is already saved but you can add a new card here if you wish to.',
  SUBSCRIBE_DESCRIPTION:
    'By confirming your subscription, you allow us to charge your card for this payment and future payments in accordance with their terms',
  STREET_TITLE: "What's your street address and n?",
  ZIP_TITLE: 'Zip code',
  DOOR_TITLE: 'Door code',
  CITY_TITLE: 'City',
  COUNTRY_TITLE: 'Country',
  PHONE_TITLE: 'Phone number',
  SWIPE_TITLE: 'Ready?',
  SWIPE_CONTENT: "Let's fine tune your style profile",
  SWIPE_RESET: 'Reset last pick',
};

export {
  PROFILE,
  FEEDBACK,
  FEEDBACK_OPTIONS,
  LOCAL_STORAGE,
  FIRESTORE_KEYS,
  HOME_DATA,
  PROFILE_DATA,
};
